name: portfolio-site
services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: portfolio_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-portfolio}
      POSTGRES_USER: ${DB_USER:-portfolio_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./SQL:/docker-entrypoint-initdb.d
    networks:
      - internal
      - npm_network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER:-portfolio_user} -d ${DB_NAME:-portfolio}",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # React frontend (production)
  app:
    container_name: portfolio_app
    build:
      context: ../
      dockerfile: docker/Dockerfile.prod
    restart: unless-stopped
    networks:
      - internal
      - npm_network
    ports:
      - "80"
    depends_on:
      - server

  # Node.js Application
  server:
    build:
      context: ../
      dockerfile: docker/Dockerfile.server
    container_name: portfolio_server
    restart: unless-stopped
    user: root
    environment:
      NODE_ENV: production
      PORT: 3000
      SITE_URL: ${SITE_URL:-http://localhost}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-portfolio}
      DB_USER: ${DB_USER:-portfolio_user}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      RECAPTCHA_SECRET_KEY: ${RECAPTCHA_SECRET_KEY}
      RECAPTCHA_VERIFY_URL: ${RECAPTCHA_VERIFY_URL}
      EMAILJS_SERVICE_ID: ${EMAILJS_SERVICE_ID}
      EMAILJS_TEMPLATE_ID: ${EMAILJS_TEMPLATE_ID}
      EMAILJS_PUBLIC_KEY: ${EMAILJS_PUBLIC_KEY}
      EMAILJS_PRIVATE_KEY: ${EMAILJS_PRIVATE_KEY}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal
      - npm_network
    ports:
      - "3000"
    volumes:
      - ../server:/usr/src/app:ro
      - ../server/public/rss:/usr/src/app/public/rss:rw
      - ../server/public/uploads:/usr/src/app/public/uploads:rw

  # Nginx Proxy Manager
  npm:
    image: jc21/nginx-proxy-manager:2.11.2
    container_name: nginx_proxy_manager
    restart: unless-stopped
    ports:
      - "81:81" # Admin UI
      - "443:443"
    environment:
      - TZ=UTC
      - DISABLE_IPV6=true
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    networks:
      - npm_network

volumes:
  postgres_data:
    driver: local
  npm_data:
    driver: local
  npm_letsencrypt:
    driver: local

networks:
  internal:
    driver: bridge
    internal: true
  npm_network:
    driver: bridge
    external: true
